version: "3"

services:
  doorbot:
    build: ./
    restart: always
    command: python /doorbot/doorbot.py
    volumes:
      - ./doorbot:/doorbot
    environment:
      TG_SECRET: "SECRET-GOES-HERE"
      PIN: 21
      ADMINS: "USERID1;USERID2;..."

  gpiod:
    image: corbosman/pigpiod
    privileged: true
    restart: always
